# Generated by Django 3.2.12 on 2022-02-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
