# Generated by Django 3.2.12 on 2022-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=200)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='spotprice',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='spotprice',
            name='base',
            field=models.CharField(default='USD', max_length=200),
            preserve_default=False,
        ),
    ]
